'''
    Enum for HRG chapter codes.
'''
from enum import StrEnum
from .probe_proto import EnumProbeMixin


class HrgChapters(EnumProbeMixin, StrEnum):
    '''
        https://gist.github.com/tomjemmett/cabdbdbb31efd457d49cd61f419b9b37
    '''
    AA = "Nervous System Procedures and Disorders"
    AB = "Pain Management"
    BZ = "Eyes and Periorbita Procedures and Disorders"
    CA = "Ear, Nose, Mouth, Throat, Head and Neck Procedures"
    CB = "Ear, Nose, Mouth, Throat, Head and Neck Disorders"
    CD = "Dental and Orthodontic Procedures"
    CZ = "Mouth Head Neck and Ears Procedures and Disorders"
    DX = "COVID-19 Infection"
    DZ = "Respiratory System Procedures and Disorders"
    EA = "Cardiac Procedures"
    EB = "Cardiac Disorders"
    EC = "Open and Interventional Procedures for Congenital Heart Disease"
    ED = "Open Cardiac Procedures for Acquired Conditions"
    EY = "Interventional Cardiology for Acquired Conditions"
    FD = "Digestive System Disorders"
    FE = "Digestive System Endoscopic Procedures"
    FF = "Digestive System Open and Laparoscopic Procedures"
    FZ = "Digestive System Procedures and Disorders"
    GA = "Hepatobiliary and Pancreatic System Open and Laparoscopic Procedures"
    GB = "Hepatobiliary and Pancreatic System Endoscopic Procedures"
    GC = "Hepatobiliary and Pancreatic System Disorders"
    HA = "Orthopaedic Trauma Procedures"
    HB = "Orthopaedic Non-Trauma Procedures"
    HC = "Spinal Procedures and Disorders"
    HD = "Musculoskeletal and Rheumatological Disorders"
    HE = "Orthopaedic Disorders"
    HN = "Orthopaedic Non-Trauma Procedures (Duplicate of HB?)"
    HR = "Orthopaedic Reconstruction Procedures"
    HT = "Orthopaedic Trauma Procedures (Duplicate of HA?)"
    JA = "Breast Procedures and Disorders"
    JB = "Burns Procedures and Disorders"
    JC = "Skin Procedures"
    JD = "Skin Disorders"
    KA = "Endocrine System Procedures and Disorders"
    KB = "Diabetic Medicine"
    KC = "Metabolic Disorders"
    LA = "Renal Procedures and Disorders"
    LB = "Urological and Male Reproductive System Procedures and Disorders"
    LC = "Renal Dialysis"
    LD = "Renal Dialysis for Chronic Kidney Disease"
    LE = "Renal Dialysis for Acute Kidney Injury"
    MA = "Female Reproductive System Procedures"
    MB = "Female Reproductive System Disorders"
    MC = "Assisted Reproduction Medicine"
    NZ = "Obstetric Medicine"
    PA = "Paediatric Medicine"
    PB = "Neonatal Disorders"
    PC = "Paediatric Ear Nose and Throat Disorders"
    PD = "Paediatric Respiratory Disorders"
    PE = "Paediatric Cardiology Disorders"
    PF = "Paediatric Gastroenterology Disorders"
    PG = "Paediatric Hepatobiliary Disorders"
    PH = "Paediatric Rheumatology Disorders"
    PJ = "Paediatric Dermatology Disorders"
    PK = "Paediatric Diabetology, Endocrinology and Metabolic Disorders"
    PL = "Paediatric Renal Disorders"
    PM = "Paediatric Haematological-Oncology Disorders"
    PN = "Paediatric Non-Malignant Haematological Disorders"
    PP = "Paediatric Ophthalmic Disorders"
    PQ = "Paediatric Immune System Disorders"
    PR = "Paediatric Nervous System Disorders"
    PT = "Paediatric Mental Health Disorders"
    PV = "Paediatric Trauma Medicine"
    PW = "Paediatric Infectious Diseases"
    PX = "Paediatric Medicine (Duplicate of PA?)"
    QZ = "Vascular Procedures and Disorders"
    RA = "Diagnostic Imaging Procedures"
    RC = "Interventional Radiology"
    RD = "Diagnostic Imaging Procedures"
    RN = "Nuclear Medicine Procedures"
    SA = "Haematological Procedures and Disorders"
    SB = "Chemotherapy"
    SC = "Radiotherapy"
    SD = "Specialist Palliative Care"
    UZ = "Undefined Groups"
    VA = "Multiple Trauma"
    VB = "Emergency Medicine"
    VC = "Rehabilitation"
    VD = "Accident and Emergency version 3.2"
    WA = "Immunology, Infectious Diseases, Poisoning, Shock, Special Examinations," \
         "Screening and Other Healthcare Contacts"
    WD = "Treatment of Mental Health Patients by Non-Mental Health Service Providers"
    WE = "Genito-Urinary Medicine"
    WF = "Non-admitted Consultations"
    WG = "Pathology"
    WH = "Poisoning, Toxic Effects, Special Examinations, Screening and Other Healthcare Contacts"
    WJ = "Infectious Diseases and Immune System Disorders"
    XA = "Neonatal Critical Care"
    XB = "Paediatric Critical Care"
    XC = "Adult Critical Care"
    XD = "High Cost Drugs"
    YA = "Neurological Imaging Interventions"
    YC = "Head and Neck Imaging Interventions"
    YD = "Thoracic Imaging Interventions"
    YF = "Gastrointestinal Imaging Interventions"
    YG = "Hepatobiliary and Pancreatic Imaging Interventions"
    YH = "Musculoskeletal Imaging Interventions"
    YJ = "Breast Imaging Interventions"
    YL = "Urological Imaging Interventions"
    YQ = "Vascular Open Procedures and Disorders"
    YR = "Vascular Imaging Interventions"
    YZ = "Other Imaging Interventions"
    ZZ = "Unbundled"

    @classmethod
    def column_name(cls) -> str:
        '''
            Returns the name of the column that contains the HRG chapter code.
        '''
        return "HRG Chapter"
