'''
    This module contains constants used in the project.
'''
# General
MAX_DIAG_COLS = 99
MAX_OPER_COLS = 99
DEFAULT_DELIMITER = "|"
APC_GROUPER_ALGORITHM = "APC"
DEFAULT_FYE_TAG = "2425"
DIAGNOSIS_PREFIX = "DIAG_"
PROCEDURE_PREFIX = "OPER_"
MAX_EPISODE_DURATION = 99999
MAX_START_AGE = 999

# File structure related
DATA_FILE_FOLDER="./data"
RAW_FILE_FOLDER=f"{DATA_FILE_FOLDER}/raw"
CACHE_FILE_FOLDER=f"{DATA_FILE_FOLDER}/cache"
HRG_INPUT_FILE_FOLDER=f"{DATA_FILE_FOLDER}/hrg_input"
HRG_OUTPUT_FILE_FOLDER=f"{DATA_FILE_FOLDER}/hrg_output"
PROCESSED_FILE_FOLDER=f"{DATA_FILE_FOLDER}/processed"

# File name related
DEFAULT_FILE_EXTENSION = ".csv"
PROBE_BASE_FILE = f"probe_base_file{DEFAULT_FILE_EXTENSION}"
SAMPLE_DATA_FILE = f"APC_Sample_Test_Data{DEFAULT_FILE_EXTENSION}"
DEFAULT_RDF_FILE="Max_OPCS_and_ICD10.rdf"
BASE_RDF_FILE="HRG4+_default_APC.rdf"
TARIFF_KV_STORE_FILE_NO_TAG = "kv_tariff_"

# File processing related
FCE_HRG_FILE_SUFFIX = "FCE"
FCE_REL_HRG_FILE_SUFFIX = "FCE_rel"
FLAG_HRG_FILE_SUFFIX = "flag_rel"
QUALITY_HRG_FILE_SUFFIX = "quality"
QUALITY_REL_HRG_FILE_SUFFIX = "quality_rel"
SORT_HRG_FILE_SUFFIX = "sort"
SPELL_HRG_FILE_SUFFIX = "spell"
SPELL_REL_HRG_FILE_SUFFIX = "spell_rel"
SUMMARY_HRG_FILE_SUFFIX = "summary"
UB_HRG_FILE_SUFFIX = "ub_rel"
TARIFF_APC_SHEET_NAME_NO_TAG = "r APC Spell Tariff"
VERSION_PREFIX = "_v"
HRG_COLUMN_NAME = "SpellHRG"
